name: tamrino
description: اپ فارسی مدیریت تمرین، آفلاین با بکاپ محلی و Google Drive
publish_to: "none"
version: 0.3.0+3

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.6
  file_picker: ^10.3.3
  google_sign_in: ^7.2.0
  googleapis: ^14.0.0
  http: ^1.5.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
